/*
 * Copyright (C) 1997-2001 Id Software, Inc.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * 
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package lwjake2.game.monsters;

public class M_Player {
    //    This file generated by qdata - Do NOT Modify

    public final static int FRAME_stand01 = 0;

    public final static int FRAME_stand10 = 9;

    public final static int FRAME_stand11 = 10;

    public final static int FRAME_stand12 = 11;

    public final static int FRAME_stand13 = 12;

    public final static int FRAME_stand14 = 13;

    public final static int FRAME_stand15 = 14;

    public final static int FRAME_stand16 = 15;

    public final static int FRAME_stand17 = 16;

    public final static int FRAME_stand18 = 17;

    public final static int FRAME_stand19 = 18;

    public final static int FRAME_stand20 = 19;

    public final static int FRAME_stand21 = 20;

    public final static int FRAME_stand22 = 21;

    public final static int FRAME_stand23 = 22;

    public final static int FRAME_stand24 = 23;

    public final static int FRAME_stand25 = 24;

    public final static int FRAME_stand26 = 25;

    public final static int FRAME_stand27 = 26;

    public final static int FRAME_stand28 = 27;

    public final static int FRAME_stand29 = 28;

    public final static int FRAME_stand30 = 29;

    public final static int FRAME_stand40 = 39;

    public final static int FRAME_run1 = 40;

    public final static int FRAME_run6 = 45;

    public final static int FRAME_attack1 = 46;

    public final static int FRAME_attack8 = 53;

    public final static int FRAME_pain101 = 54;

    public final static int FRAME_pain102 = 55;

    public final static int FRAME_pain103 = 56;

    public final static int FRAME_pain104 = 57;

    public final static int FRAME_pain201 = 58;

    public final static int FRAME_pain202 = 59;

    public final static int FRAME_pain203 = 60;

    public final static int FRAME_pain204 = 61;

    public final static int FRAME_pain301 = 62;

    public final static int FRAME_pain302 = 63;

    public final static int FRAME_pain303 = 64;

    public final static int FRAME_pain304 = 65;

    public final static int FRAME_jump1 = 66;

    public final static int FRAME_jump2 = 67;

    public final static int FRAME_jump3 = 68;

    public final static int FRAME_jump6 = 71;

    public final static int FRAME_flip01 = 72;

    public final static int FRAME_flip12 = 83;

    public final static int FRAME_salute01 = 84;

    public final static int FRAME_salute11 = 94;

    public final static int FRAME_taunt01 = 95;

    public final static int FRAME_taunt17 = 111;

    public final static int FRAME_wave01 = 112;

    public final static int FRAME_wave08 = 119;

    public final static int FRAME_wave11 = 122;

    public final static int FRAME_point01 = 123;

    public final static int FRAME_point12 = 134;

    public final static int FRAME_crstnd01 = 135;

    public final static int FRAME_crstnd19 = 153;

    public final static int FRAME_crwalk1 = 154;

    public final static int FRAME_crwalk6 = 159;

    public final static int FRAME_crattak1 = 160;

    public final static int FRAME_crattak3 = 162;

    public final static int FRAME_crattak9 = 168;

    public final static int FRAME_crpain1 = 169;

    public final static int FRAME_crpain4 = 172;

    public final static int FRAME_crdeath1 = 173;

    public final static int FRAME_crdeath5 = 177;

    public final static int FRAME_death101 = 178;

    public final static int FRAME_death106 = 183;

    public final static int FRAME_death201 = 184;

    public final static int FRAME_death206 = 189;

    public final static int FRAME_death301 = 190;

    public final static int FRAME_death308 = 197;

    public final static float MODEL_SCALE = 1.000000f;

}